src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`users`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email]
    #[Assert\Length(max: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    #[Assert\Length(min: 2, max: 50)]
    private ?string $userName = null;

    #[ORM\OneToMany(targetEntity: RoomSession::class, mappedBy: 'creator', orphanRemoval: true)]
    private Collection $createdRoomSessions;

    #[ORM\Column(type: 'boolean')]
    private bool $isVerified = false;

    #[ORM\Column(options: ["default" => false])]
    private ?bool $isSuspended = false;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $suspendedAt = null;

    public function __construct()
    {
        $this->createdRoomSessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;
        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->userName;
    }

    public function setUserName(?string $userName): static
    {
        $this->userName = $userName;
        return $this;
    }

    /**
     * @return Collection<int, RoomSession>
     */
    public function getCreatedRoomSessions(): Collection
    {
        return $this->createdRoomSessions;
    }

    public function addCreatedRoomSession(RoomSession $createdRoom): static
    {
        if (!$this->createdRoomSessions->contains($createdRoom)) {
            $this->createdRoomSessions->add($createdRoom);
            $createdRoom->setCreator($this);
        }

        return $this;
    }

    public function removeCreatedRoomSession(RoomSession $createdRoom): static
    {
        if ($this->createdRoomSessions->removeElement($createdRoom)) {
            // set the owning side to null (unless already changed)
            if ($createdRoom->getCreator() === $this) {
                $createdRoom->setCreator(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getUserIdentifier();
    }

    public function isSuspended(): ?bool
    {
        return $this->isSuspended;
    }

    public function setIsSuspended(bool $isSuspended): static
    {
        $this->isSuspended = $isSuspended;

        return $this;
    }

    public function getSuspendedAt(): ?\DateTimeImmutable
    {
        return $this->suspendedAt;
    }

    public function setSuspendedAt(\DateTimeImmutable $suspendedAt): static
    {
        $this->suspendedAt = $suspendedAt;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();



        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/common.html.twig
{% extends 'base.html.twig' %}

{% block body_background %}style="background-image: url('{{ asset('images/intro.jpg') }}'); background-size: cover"{% endblock %}

{% block body %}
        <div class="container">
            <div class="row g-2 justify-content-center py-4 vh-100">
                <div class="col-md-4 order-2 order-md-1 d-flex">
                    <div class="m-auto bg-white p-3 rounded">
                        <h3>{{ 'security.common.why_account.title' | trans({serviceName: serviceName}) }}</h3>
                        <p>{{ 'security.common.why_account.desc' | trans }}</p>
                        <h3>{{ 'security.common.how_data.title' | trans }}</h3>
                        <p>{{ 'security.common.how_data.desc' | trans }}</p>
                    </div>
                </div>
                <div class="col-lg-4 order-1 order-md-1 d-flex">
                    {% block login_form %}{% endblock %}
                </div>
            </div>
        </div>
{% endblock %}

templates/security/login.html.twig
{% extends 'security/common.html.twig' %}

{% block title %}{{ 'login.title' | trans }}{% endblock %}

{% block login_form %}
            <form method="post" class="w-100 mx-auto my-lg-auto p-3 bg-white rounded" style="max-width: 400px" data-turbo="false">
                {% if error %}
                    <div class="alert alert-danger" role="alert">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}

                {% for label, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="alert alert-{{ label }}" role="alert">{{ message | trans }}</div>
                    {% endfor %}
                {% endfor %}

                {% if app.user %}
                    <div class="mb-3">
                        You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                    </div>
                {% endif %}

                <p class="h3 mb-3 fw-normal">{{ 'login.desc' | trans }}</p>
                <div class="form-floating mb-3">
                    <input type="email" value="{{ last_username }}" name="_username" id="username" class="form-control" autocomplete="email" required autofocus placeholder="name@example.com">
                    <label for="username">{{ 'login.form.email' | trans }}</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" name="_password" id="password" class="form-control" autocomplete="current-password" required placeholder="Password">
                    <label for="password">{{ 'login.form.password' | trans }}</label>
                </div>

                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

                <button class="btn btn-primary w-100 py-2 mb-2" type="submit">
                    {{ 'login.sign_in_btn' | trans }}
                </button>

                <hr>

                <p class="mt-3 text-center">{{ 'login.no_account.title' | trans }} <a href="{{ path('app_register') }}">{{ 'login.no_account.link' | trans }}</a></p>
                <p class="mt-3 text-center">{{ 'login.pw_forgotten.title' | trans }} <a class="text-nowrap" href="{{ path('app_forgot_password_request') }}">{{ 'login.pw_forgotten.link' | trans }}</a></p>
            </form>
{% endblock %}